### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Kobrasadetin** [minttu/ernu#7]
Ladattu 6.1. klo 11:36

Ihan aluksi täytyy sanoa että projekti vaikuttaa todella hyvin toteutetulta. Luokissa on noudatettu single responsibility -periaatetta ja koodi on siistiä ja selkeästi jäsenneltyä, kaiken kaikkiaan erinomaista työtä. Oma ohjelmointitaitoni ei riitä kommentoimaan sitä, olisiko jokin ohjelmalogiikan osa kannattanut toteuttaa toisin. Ennemminkin lähdekoodin tutkiminen on ollut itselleni oppimiskokemus. 

Projektin buildaamisessa törmäsin ongelmiin, varmaan ihan omaa kädettömyyttäni. Ihan aluksi git-commit-id-plugin -plugari ei suostunut toimimaan. Sain seuraavan virheilmoituksen:
<i>Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.12:revision (default) on project ernu: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]</i>

Kun en löytänyt muutakaan ratkaisua, poistin plugarin pomista.
Buildissa yksi testi epäonnistui (fi.imberg.juhani.ernu.interpreter.builtin.PrintFunctionTest).
Liittyikö testin epäonnistuminen pomin silpomiseen vai ei, en osaa sanoa. Kivasti ohjelma kuitenkin kääntyi ja vaikutti toimivan oletetusti. Versionumero ei tietysti näkynyt. Sellaisen ominaisuuden huomasin, että toistolausekkeen kirjoittaminen REPL-komentoriville aiheuttaa NoSuchElementException -poikkeuksen.

Dokumentaation puolesta käyttöohjeen ja esimerkkiohjelmien olemassaolo on erinomainen juttu, ja käyttöohje on hyvin kirjoitettu.

Kun en itse osannut löytää moitittavaa, kävin lunttaamassa mitä sanottavaa tilastokeskus oli edellisessä katselmoinnissa keksinyt. Silmäillen näytti siltä että ainakin kaikki mainitsemansa ongelmakohdat ovat hyvällä mallilla projektin nykyisessä versiossa.

**Comment by Kobrasadetin** [comment]
Unohtui mainita:
ladattu 6.1. klo 11:36

**Comment by JuhaniImberg** [comment]
Jepjep, oletin että ihmiset git clonaa eikä lataa zippejä, joten tuo `git-commit-id-plugin` tosiaan oisi halunnut gitrepon, siinä missä githubista ladattu zip ei sisällä oikeastaan gittiä. Toistolausekkeen kohdalla se pitää kirjoittaa kaikki yhdelle riville REPLissä, esim

    for i in range(10) do print(i) end

Tämä johtuu siitä että jokainen rivi halutaan evaluoida kokonaisena arvona tms.

Kiitos palautteesta!
